[build]
  publish = "."
  command = "echo 'No build command needed for Flask app'"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/app.py"
  status = 200
  force = true

[functions]
  directory = "."
  included_files = ["**/*.py", "**/*.html", "**/*.css", "**/*.js", "**/*.png", "**/*.jpg", "**/*.svg", "**/*.webp", "**/*.apk"]
